### ISSUE TITLE
README.md -ak zaindu

### ISSUE THREAD

**Issue by imadariaga** [UnaiZelaia/datu-atzipena23-24#2]
Irakurri "[Kontutan eduki beharrekoak](https://elearning20.hezkuntza.net/012053/mod/assign/view.php?id=15076)"

**Comment by UnaiZelaia** [comment]
Ezteka jartzen duena irakurri dut eta ez dakit zein den arazoa. Gehiago konkretatu edo Issue hau itxi egingo dut.
